trigger:
    - main

pool:
    vmImage: ubuntu-latest

steps:
    - task: DotNetCoreCLI@2
      inputs:
          command: "restore"
          projects: "./RedOps.sln"
          feedsToUse: "config"
          nugetConfigPath: "./nuget.config"
          noCache: true

    - task: DotNetCoreCLI@2
      inputs:
          command: "build"
          projects: "./RedOps.sln"

    - task: DotNetCoreCLI@2
      inputs:
          command: "test"
          projects: "./RedOps.sln"

    - task: DotNetCoreCLI@2
      inputs:
          command: "publish"
          publishWebProjects: false
          projects: "./RedOps.sln"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        StoreAsTar: true